### ISSUE TITLE
Installing Docker on Windows Home or older Windows

### ISSUE THREAD

**Issue by lhami** [xw0078/VT_Fall18_CS4984-CS5984#1]
Instead of downloading Docker CE, you'll need to download the Docker Toolbox at [https://docs.docker.com/toolbox/toolbox_install_windows/](https://docs.docker.com/toolbox/toolbox_install_windows/)

Open Task Manager > Performance and check if Virtualization is enabled. If not, boot into the BIOS or UEFI menu. Find the "Virtualization Extensions" setting and enable it.

You'll want to run the "Docker Quickstart Terminal" to download the image.

**Comment by xw0078** [comment]
Hi, thanks for the note.
Could you specify the Windows version you are running?

**Comment by lhami** [comment]
I'm running Windows 10 Home 64-Bit. If you try to download the Docker CE on Windows 10 Home or any older version of Windows, it will give an error saying that your computer needs to support Hyper-V virtualization and end the installation. It says this on the download page for Docker CE:

> Requires Microsoft Windows 10 Professional or Enterprise 64-bit. For previous versions get Docker Toolbox.

I have successfully gotten Docker Toolbox running, though. The main difference from what I can tell seems to be the lack of UI.

**Comment by xw0078** [comment]
@lhami Thank you for the notes :)

I have updated a new section for Windows10 installation through Docker Toolbox. 

It appears that Docker for Windows is using Hyper-V as the VM engine, which is only supported by Windows10 Pro. 

Docker Toolbox, on the other hand, is using a Virtual Box as the VM engine, which is more universal.
